version: '2'
services:
    apache:
        build: ./apache 
        links:
          - postgres_9.4:db-postgres
        ports:
          - "127.0.0.1:8080:80"
        volumes:
          - moodledata:/srv/moodledata
          - moodlecode:/var/www/moodle # Mounting Moodle code from the volume.
        depends_on:
          - postgres_9.4
#        environment:
#            DISABLE_CLAMD: 'true'
    postgres_9.4:
        image: postgres:9.4
        volumes:
          - pgdata:/var/lib/postgresql/data
    cron:
        build: ./cron
        links:
          - postgres_9.4:db-postgres
        volumes:
          - moodledata:/srv/moodledata
          - moodlecode:/var/www/moodle # Mounting Moodle code from the volume.
        depends_on:
          - postgres_9.4
volumes:
    moodledata:
        external: true
    moodlecode: # Used by docker-sync-example.yml for Moodle code syncing. 
        external: true
    pgdata:
        external: true

