# Docker Compose file for moodle dev environment.
# Use docker-compose.override.yml to override setting below.
version: '2'
services:
    moodle:
        image: lucisgit/docker-moodle-apache-dev:latest
        links:
          - postgres_9.4:db-postgres
#        ports:
#          - "80:80"
#          - "443:443"
        volumes:
          - moodledata:/srv/moodledata
#          - /home/username/git/moodle:/var/www/moodle # Mounting Moodle code from the host location.see docker-compose.override-example for details.
        depends_on:
          - postgres_9.4
#        environment:
#            DISABLE_CLAMD: 'true'
    postgres_9.4:
        image: postgres:9.4
        volumes:
          - pgdata:/var/lib/postgresql/data
        ports:
          - "5432:5432"
    cron:
        image: lucisgit/docker-moodle-cron-dev:latest
        links:
          - postgres_9.4:db-postgres
        volumes:
          - moodledata:/srv/moodledata
#          - /home/username/git/moodle:/var/www/moodle # Mounting Moodle code from the host location.
        depends_on:
          - postgres_9.4
volumes:
    moodledata:
        external: true
    pgdata:
        external: true

